import type { Metadata } from "next";
import { Michroma, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

const michroma = Michroma({
    weight: "400",
    variable: "--font-michroma",
    subsets: ["latin"],
    display: "swap",
});

const ibmPlexMono = IBM_Plex_Mono({
    weight: ["300", "400", "500", "600", "700"],
    variable: "--font-ibm-plex-mono",
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="ja"
            className={`${michroma.variable} ${ibmPlexMono.variable}`}
        >
            <body className="font-sans min-h-screen bg-background text-foreground antialiased">
                <main>{children}</main>
                {/* <Toaster richColors position="top-right" /> */}
            </body>
        </html>
    );
}
